[package]
name = "swarm"
version = "0.1.0"
authors = ["KT"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
globwalk = "0.8.0"
rayon = "1.3.0"
num_cpus = "1.0"