pub struct Symbol {
    pub id: String,
    pub kind: SymbolKind,
    pub name: String,
    pub start_line: u32,
    pub end_line: u32,
    pub start_column: u32,
    pub end_column: u32,
    pub is_container: bool,
    pub file_path: String,
    pub file_last_write: u32,
    pub container: String,
    pub container_kind: SymbolKind,
    pub container_line: u32,
    pub is_end_declaration: bool,
}

pub enum SymbolKind {
    File,
    Module,
    Namespace,
    Package,
    Class,
    Method,
    Property,
    Field,
    Constructor,
    Enum,
    Interface,
    Function,
    Variable,
    Constant,
    String,
    Number,
    Boolean,
    Array,
    Object,
    Key,
    Null,
    EnumMember,
    Struct,
    Event,
    Operator,
    TypeParameter,
}
